services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: seyan99
      POSTGRES_PASSWORD: admin1112
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped

  config-server-ms:
    image: seyan99/config-server-image:latest
    container_name: config-server-jobapp
    ports:
      - 8080:8080
    depends_on:
      - eureka-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 768M
        reservations:
          cpus: 0.25
          memory: 128M

  eureka-server-ms:
    image: seyan99/eureka-server-image:latest
    container_name: eureka-server-jobapp
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network
      - postgres
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 768M
        reservations:
          cpus: 0.25
          memory: 128M

  company-ms:
    image: seyan99/company-image:latest
    container_name: company
    ports:
      - 8081:8081
    depends_on:
      - eureka-server-ms
      - config-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 768M
        reservations:
          cpus: 0.25
          memory: 128M

  job-ms:
    image: seyan99/job-image:latest
    container_name: job
    ports:
      - 8082:8082
    depends_on:
      - eureka-server-ms
      - config-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL-DEFAULTZONE=http://eureka-server-jobapp:8761/eureka
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 768M
        reservations:
          cpus: 0.25
          memory: 128M

  review-ms:
    image: seyan99/review-image:latest
    container_name: review
    ports:
      - 8083:8083
    depends_on:
      - eureka-server-ms
      - config-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 768M
        reservations:
          cpus: 0.25
          memory: 128M

  gateway-ms:
    image: seyan99/gateway-image:latest
    container_name: gateway
    ports:
      - 8765:8765
    depends_on:
      - eureka-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - postgres
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - postgres
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M

networks:
  microservice-network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: